CREATE SEQUENCE seq_film START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_versiune_film START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_client START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_actor START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_vizualizare START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_vot START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_comentariu START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_feedback START WITH 1 INCREMENT BY 1;